name: Angular CI

on:
  push:
    branches: [ "test" ]
env:
  IMAGE_NAME: angular 
jobs:
  test:
     runs-on: ubuntu-latest
     strategy:
         fail-fast: true
     steps:
     - name: clone repo
       uses: actions/checkout@v1
     - name: setup node
       uses: actions/setup-node@v1
       with:
        node-version:  '18.6'
     - name: test angular
       run: |
        npm install
        npm run test -- --watch=false --browsers=ChromeHeadless
       working-directory: angular
  
  build:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - name: clone repo
      uses: actions/checkout@v1
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '18.6'
    - name: build angular
      run: |
        npm install
        npm run build --if-present
      working-directory: angular    
    - name: cache files
      uses: actions/cache@v3
      with:
        path: |
          ./angular
          ./nginx.conf
          ./Dockerfile
        key:  angular-${GITHUB_SHA::7}
  push:
    needs: [test,build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - name: login github registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: restore cache
      uses: actions/cache@v3
      with:
       path:  |
          ./angular
          ./nginx.conf
          ./Dockerfile
       key: angular-${GITHUB_SHA::7}
    - name: build image
      run: docker build -t $IMAGE_NAME:${GITHUB_SHA::7} .
    - name: tag image
      run: |
         export IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
           docker tag $IMAGE_NAME:${GITHUB_SHA::7} $IMAGE_ID:${GITHUB_SHA::7}
    - name: push image
      run: |
       echo $IMAGE_ID
       docker push $IMAGE_ID:${GITHUB_SHA::7}
