# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: all-stack CI

on:
  push:
    branches: [ "test" ]
env:
  IMAGE_NAME: all-stack

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.6]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v1
    - name: Check files
      run: ls -la
    - name: Send mail
      uses: dawidd6/action-send-mail@v3.6.1
      with:
    # Required mail server address:
        server_address: smtp.gmail.com
    # Required mail server port:
        server_port: 465
    # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
    # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
    # Required mail subject:
        subject: Github Actions job result
    # Required recipients' addresses:
        to: prutkov.work@gmail.com
    # Required sender full name (address can be skipped):
        from: Frey # <user@example.com>
    # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
    # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
