# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: all-stack CI

on:
  push:
    branches: [ "test" ]
env: 
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: all-stack


jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - name: Check files!
      run: ls -la
    - name: Echo GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT
    - run: exit 1



  notification:
   runs-on: ubuntu-latest
   needs: build
   if: ${{ always() }}
   steps:
    - uses: actions/checkout@v1
    - run: | 
        echo "result build: ${{ needs.build.result }}"
    - name: Check files!
      run: ls -la
    - name: Echo GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT
    - name: Get time
      run: |
        gh api \
        -H "Accept: application/vnd.github+json" \
        /repos/frayme/angular-react-starter/actions/runs/${{github.run_id}}/timing > 1.json \
        && cat 1.json
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
    # App password for from google acc.
        password: ${{secrets.MAIL_PASSWORD}}
    # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    #  send email to
        to: prutkov.work@gmail.com
    # from email name
        from: ${{ github.repository_owner }}
   
