# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: all-stack CI

on:
  push:
    branches: [ "test" ]
env:
  IMAGE_NAME: all-stack

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.6]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v1
    - name: Check files
      run: ls -la
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
    # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
    # user credentials
      env:
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.mail_pass}}
    # email subject
      subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
      body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    # comma-separated string, send email to
      to: prutkov.work@gmail.com
    # from email name
      from: John Doe
